version: 2
jobs:
  build_and_deploy:
    docker:
      - image: microsoft/dotnet:2.2-sdk

      - run: 
         name: Build
         command: |
            dotnet build 
      #- run: dotnet test --no-build --logger "trx"
      - run:
          name: Run tests
          command: |
            dotnet test --logger trx --results-directory "..\TestResults"

            # ...

      - run:
          name: Install TRX 2 JUnit converter
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g trx2junit
          when: always

      - run:
          name: Convert TRX test results to JUnit format
          command: |
            /root/.dotnet/tools/trx2junit TestResults/*.trx
          when: always

      - store_test_results:
          path: TestResults

