version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: microsoft/dotnet:3.1-sdk

    steps:
      - checkout
      - run: dotnet build
          command: |
            dotnet test --logger trx --results-directory "..\TestResults"
      - run:
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install -g trx2junit
          when: always
      - run:
          command: |
            /root/.dotnet/tools/trx2junit TestResults/*.trx
          when: always
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: tests/TestResults
          destination: TestResults

